name: CI for Chrome Extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate manifest.json
        run: |
          jq -e . manifest.json >/dev/null || (echo "Erro: manifest.json inválido" && exit 1)

      - name: Package Chrome extension
        run: |
          mkdir -p dist
          zip -r dist/extension.zip . -x "node_modules/*" "dist/*" ".git/*" ".github/*"

      - name: Verify zip creation
        run: |
          if [ ! -f dist/extension.zip ]; then echo "Erro: dist/extension.zip não foi criado"; exit 1; fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: dist/extension.zip
